platform:
  - x86
  - x64

branches:
  except:
    - gh-pages

environment:
  matrix:
    - RUST_VERSION: 1.0.0
    - RUST_VERSION: beta
    - RUST_VERSION: nightly

install:
  - ps: |
      if ($env:PLATFORM -eq "x86") {
        Start-FileDownload "https://static.rust-lang.org/dist/rust-$env:RUST_VERSION-i686-pc-windows-gnu.exe" -FileName rust.exe
      } else {
        Start-FileDownload "https://static.rust-lang.org/dist/rust-$env:RUST_VERSION-x86_64-pc-windows-gnu.exe" -FileName rust.exe
      }
  - rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
  - SET PATH=%PATH%;C:\Program Files\Rust\bin;C:\Python27;C:\Python27\Scripts
  - rustc -V
  - cargo -V
  - pip install ghp-import

build: false

test_script:
  - cargo test -v

deploy_script:
  - cargo doc
  - python C:\Python27\Scripts\ghp-import -n target/doc
  - git push -qf https://%GH_TOKEN%@github.com/%APPVEYOR_REPO_NAME%.git gh-pages