platform:
  - x86
  - x64

branches:
  except:
    - gh-pages

environment:
  matrix:
    # Rust 1.3 required for $ty followed by ; in com_interface! macro
    # - RUST_VERSION: 1.3.0
    - RUST_VERSION: beta
      RUST_TOOLCHAIN: gnu
    - RUST_VERSION: beta
      RUST_TOOLCHAIN: msvc
    - RUST_VERSION: nightly
      RUST_TOOLCHAIN: gnu
    - RUST_VERSION: nightly
      RUST_TOOLCHAIN: msvc

install:
  - ps: |
      if ($env:PLATFORM -eq "x86") {
        Start-FileDownload "https://static.rust-lang.org/dist/rust-$env:RUST_VERSION-i686-pc-windows-$env:RUST_TOOLCHAIN.exe" -FileName rust.exe
      } else {
        Start-FileDownload "https://static.rust-lang.org/dist/rust-$env:RUST_VERSION-x86_64-pc-windows-$env:RUST_TOOLCHAIN.exe" -FileName rust.exe
      }
  - rust.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
  - SET PATH=%PATH%;C:\Program Files\Rust\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo test -v
